version: '3'

services:

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
  redis:
    container_name: "redis"
    image: redis
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass mypassword
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
